export interface Language {
  code: string; // ISO 639-1 (or ISO 639-2 if no ISO 639-1 code exists)
  englishName: string; // Language name in English
  nativeName: string; // Language name in its native script
}

export const AVAILABLE_LANGUAGES: Language[] = [
  { code: "af", englishName: "Afrikaans", nativeName: "Afrikaans" },
  { code: "sq", englishName: "Albanian", nativeName: "Shqip" },
  { code: "am", englishName: "Amharic", nativeName: "አማርኛ" },
  { code: "ar", englishName: "Arabic", nativeName: "العربية" },
  { code: "hy", englishName: "Armenian", nativeName: "Հայերեն" },
  { code: "az", englishName: "Azerbaijani", nativeName: "Azərbaycanca" },
  { code: "bn", englishName: "Bengali", nativeName: "বাংলা" },
  { code: "bs", englishName: "Bosnian", nativeName: "Bosanski" },
  { code: "bg", englishName: "Bulgarian", nativeName: "Български" },
  { code: "my", englishName: "Burmese", nativeName: "မြန်မာဘာသာ" },
  { code: "ca", englishName: "Catalan", nativeName: "Català" },
  { code: "zh", englishName: "Chinese", nativeName: "中文" },
  { code: "hr", englishName: "Croatian", nativeName: "Hrvatski" },
  { code: "cs", englishName: "Czech", nativeName: "Čeština" },
  { code: "da", englishName: "Danish", nativeName: "Dansk" },
  { code: "nl", englishName: "Dutch", nativeName: "Nederlands" },
  { code: "dz", englishName: "Dzongkha", nativeName: "རྫོང་ཁ" },
  { code: "en", englishName: "English", nativeName: "English" },
  { code: "et", englishName: "Estonian", nativeName: "Eesti" },
  { code: "fi", englishName: "Finnish", nativeName: "Suomi" },
  { code: "fr", englishName: "French", nativeName: "Français" },
  { code: "gl", englishName: "Galician", nativeName: "Galego" },
  { code: "ka", englishName: "Georgian", nativeName: "ქართული" },
  { code: "de", englishName: "German", nativeName: "Deutsch" },
  { code: "el", englishName: "Greek", nativeName: "Ελληνικά" },
  { code: "gu", englishName: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "ht", englishName: "Haitian Creole", nativeName: "Kreyòl ayisyen" },
  { code: "he", englishName: "Hebrew", nativeName: "עברית" },
  { code: "hi", englishName: "Hindi", nativeName: "हिन्दी" },
  { code: "hu", englishName: "Hungarian", nativeName: "Magyar" },
  { code: "is", englishName: "Icelandic", nativeName: "Íslenska" },
  { code: "id", englishName: "Indonesian", nativeName: "Bahasa Indonesia" },
  { code: "ga", englishName: "Irish", nativeName: "Gaelige" },
  { code: "it", englishName: "Italian", nativeName: "Italiano" },
  { code: "ja", englishName: "Japanese", nativeName: "日本語" },
  { code: "kk", englishName: "Kazakh", nativeName: "Қазақша" },
  { code: "km", englishName: "Khmer", nativeName: "ខ្មែរ" },
  { code: "rw", englishName: "Kinyarwanda", nativeName: "Ikinyarwanda" },
  { code: "ko", englishName: "Korean", nativeName: "한국어" },
  { code: "ky", englishName: "Kyrgyz", nativeName: "Кыргызча" },
  { code: "lo", englishName: "Lao", nativeName: "ລາວ" },
  { code: "lv", englishName: "Latvian", nativeName: "Latviešu" },
  { code: "lt", englishName: "Lithuanian", nativeName: "Lietuvių" },
  { code: "lb", englishName: "Luxembourgish", nativeName: "Lëtzebuergesch" },
  { code: "mk", englishName: "Macedonian", nativeName: "Македонски" },
  { code: "mg", englishName: "Malagasy", nativeName: "Malagasy" },
  { code: "ms", englishName: "Malay", nativeName: "Bahasa Melayu" },
  { code: "mt", englishName: "Maltese", nativeName: "Malti" },
  { code: "mn", englishName: "Mongolian", nativeName: "Монгол" },
  { code: "ne", englishName: "Nepali", nativeName: "नेपाली" },
  { code: "no", englishName: "Norwegian", nativeName: "Norsk" },
  { code: "ps", englishName: "Pashto", nativeName: "پښتو" },
  { code: "fa", englishName: "Persian", nativeName: "فارسی" },
  { code: "pl", englishName: "Polish", nativeName: "Polski" },
  { code: "pt", englishName: "Portuguese", nativeName: "Português" },
  { code: "pa", englishName: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
  { code: "ro", englishName: "Romanian", nativeName: "Română" },
  { code: "ru", englishName: "Russian", nativeName: "Русский" },
  { code: "sm", englishName: "Samoan", nativeName: "Gagana Samoa" },
  { code: "sr", englishName: "Serbian", nativeName: "Српски" },
  { code: "sn", englishName: "Shona", nativeName: "ChiShona" },
  { code: "si", englishName: "Sinhala", nativeName: "සිංහල" },
  { code: "sk", englishName: "Slovak", nativeName: "Slovenčina" },
  { code: "sl", englishName: "Slovenian", nativeName: "Slovenščina" },
  { code: "so", englishName: "Somali", nativeName: "Soomaali" },
  { code: "es", englishName: "Spanish", nativeName: "Español" },
  { code: "sw", englishName: "Swahili", nativeName: "Kiswahili" },
  { code: "sv", englishName: "Swedish", nativeName: "Svenska" },
  { code: "tl", englishName: "Tagalog", nativeName: "Tagalog" },
  { code: "tg", englishName: "Tajik", nativeName: "Тоҷикӣ" },
  { code: "ta", englishName: "Tamil", nativeName: "தமிழ்" },
  { code: "te", englishName: "Telugu", nativeName: "తెలుగు" },
  { code: "th", englishName: "Thai", nativeName: "ไทย" },
  { code: "to", englishName: "Tongan", nativeName: "Lea Faka-Tonga" },
  { code: "tr", englishName: "Turkish", nativeName: "Türkçe" },
  { code: "tk", englishName: "Turkmen", nativeName: "Türkmençe" },
  { code: "uk", englishName: "Ukrainian", nativeName: "Українська" },
  { code: "ur", englishName: "Urdu", nativeName: "اردو" },
  { code: "uz", englishName: "Uzbek", nativeName: "O‘zbek" },
  { code: "vi", englishName: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "xh", englishName: "Xhosa", nativeName: "isiXhosa" },
  { code: "zu", englishName: "Zulu", nativeName: "isiZulu" },
];

export const SUPPORTED_APP_LANGUAGE: Language[] = [
  { code: "en", englishName: "English", nativeName: "English" },
  { code: "vi", englishName: "Vietnamese", nativeName: "Tiếng Việt" },
  { code: "zh", englishName: "Chinese", nativeName: "中文" },
  { code: "ja", englishName: "Japanese", nativeName: "日本語" },
  { code: "ko", englishName: "Korean", nativeName: "한국어" },
  { code: "fr", englishName: "French", nativeName: "Français" },
  { code: "es", englishName: "Spanish", nativeName: "Español" },
  { code: "de", englishName: "German", nativeName: "Deutsch" },
];

export const SUPPORTED_TRANSLATED_LANGUAGE = AVAILABLE_LANGUAGES;

export const DEFAULT_LANGUAGE_CODE = "en";
